### ISSUE TITLE
Latest beta updates crash Retrobat with Platform and ArcadeForever, snaps play audio only

### ISSUE THREAD

**Issue by ghost** [lehcimcramtrebor/es-theme-platform#1]
Hi Lehcim,

At least from Retrobat 4.0 beta 3 update 31.0.0-202119182219 several themes crash RetroBat when displaying videos, including Platform and Arcade Forever. We get audio from the snaps but not video on these themes, and sometimes crashes when using them.

Attached debug mode es_log.txt , using a clean Retrobat 4.0 beta 3 + all beta updates (including from #📢announcements-eng )

[es_log.zip](https://github.com/lehcimcramtrebor/es-theme-platform/files/6360830/es_log.zip)

Cheers,
Bilu

**Comment by lehcimcramtrebor** [comment]
No problem with theme, don’t use emulationstation in développement version.
